version: '3'
services:
  ${DB_SERVICE_NAME}:
    container_name: jairu-db
    image: mysql
    #    working_dir: /jairu/db
    volumes:
      - jairu-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  #    networks:
  #      mcr_net:
  #        ipv4_address: 172.30.3.1

  ${BACKEND_SERVICE_NAME}:
    container_name: jairu-backend
    image: murphy961/jairu-backend:1.0
    working_dir: /jairu/backend
    volumes:
      - jairu-backend-vol:/jairu/backend
    stdin_open: true
    expose:
      - ${BACKEND_EXPOSE_PORT}
    ports:
      - ${BACKEND_EXPOSE_PORT}:${BACKEND_INTERNAL_PORT}"
    depends_on:
      - jairu-db
    #    networks:
    #      mcr_net:
    #        ipv4_address: 172.30.3.2
    restart: unless-stopped
    environment:
      DB_SERVICE_NAME: ${DB_SERVICE_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      BACKEND_INTERNAL_PORT: ${BACKEND_INTERNAL_PORT}

  ${FRONTEND_SERVICE_NAME}:
    container_name: jairu-frontend
    image: murphy961/jairu-frontend:1.0
    working_dir: /jairu/frontend
    stdin_open: true
    expose:
      - ${FRONTEND_EXPOSE_PORT}
    ports:
      - ${FRONTEND_EXPOSE_PORT}:${FRONTEND_EXPOSE_PORT}
    depends_on:
      - jairu-backend
    #    networks:
    #      mcr_net:
    #        ipv4_address: 172.30.3.3
    restart: unless-stopped

volumes:
  jairu-db-vol:
  jairu-backend-vol:


#networks:
#  jairu-net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.30.3.0/24
