version: '3'
services:
  jairu-db:
    container_name: jairu-db
    image: mysql
    #    working_dir: /jairu/db
    volumes:
      - jairu-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: murphy
      MYSQL_PASSWORD: Murphy@961
      MYSQL_DATABASE: jairu
  #    networks:
  #      mcr_net:
  #        ipv4_address: 172.30.3.1

  jairu-backend:
    container_name: jairu-backend
    image: murphy961/jairu-backend:1.0
    working_dir: /jairu/backend
    volumes:
      - jairu-backend-db:.
    stdin_open: true
    expose:
      - 8086
    ports:
      - 8086:8086
    depends_on:
      - jairu-db
    #    networks:
    #      mcr_net:
    #        ipv4_address: 172.30.3.2
    restart: unless-stopped

  jairu-frontend:
    container_name: jairu-frontend
    image: murphy961/jairu-frontend:1.0
    working_dir: /jairu/frontend
    stdin_open: true
    expose:
      - 8087
    ports:
      - 8087:80
    depends_on:
      - jairu-backend
    #    networks:
    #      mcr_net:
    #        ipv4_address: 172.30.3.3
    restart: unless-stopped

volumes:
  jairu-db-vol:
  jairu-backend-vol:


#networks:
#  jairu-net:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.30.3.0/24
