version: '3'
services:
  jairu-db:
    container_name: jairu-db
    image: mysql
    volumes:
      - jairu-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  jairu-backend:
    container_name: jairu-backend
    image: murphy961/jairu-backend:1.0
    working_dir: /jairu/backend
    volumes:
      - jairu-backend-vol:/jairu/backend
    stdin_open: true
    expose:
      - 8086
    ports:
      - 8086:8086
    depends_on:
      - jairu-db
    restart: unless-stopped
    environment:
      DB_SERVICE_NAME: ${DB_SERVICE_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      BACKEND_INTERNAL_PORT: ${BACKEND_INTERNAL_PORT}

  jairu-frontend:
    container_name: jairu-frontend
    image: murphy961/jairu-frontend:1.0
    working_dir: /jairu/frontend
    stdin_open: true
    expose:
      - 8087
    ports:
      - 8087:80
    depends_on:
      - jairu-backend
    restart: unless-stopped

volumes:
  jairu-db-vol:
  jairu-backend-vol:
