#- name: Deploying 'JAIRU' Project
#  hosts: all
#  become: yes
#  tasks:
#    - name: stop all the services
#      shell:
#        docker-compose up -d
#    - name: start all the services
#      shell:
#        docker-compose up -d
# downloading docker-compose
#  rm /usr/local/bin/docker-compose||ls&&curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose&&chmod +x /usr/local/bin/docker-compose

- name: Run Docker Compose file on VM
  hosts: all
  become: yes

  tasks:
    - name: Copy Docker Compose file to VM
      copy:
        src: /var/lib/jenkins/workspace/JAIRU-Frontend/docker-compose.yaml
        dest: ./docker-compose.yaml

    - name: stop all the services
      shell:
        docker-compose down
    - name: start all the services
      shell:
        docker-compose up -d
